/*
 *rn--内部跳转路由集合
 */

export const RouterPaths = {
    CHOSE_OCCUPATION:"occupationSelection",
    TRANSACTION_DETAILS: "transactionDetails",
    SPLASH_PAGE: 'splash',
    HOME_PAGE: 'home',
    CHOSE_CITY: 'choseCity',
    CHANGE_NAME_PAGE: 'changeName',
    FEEDBACK_PAGE: 'feedback',
    SETTING_PAGE: 'setting',
    PERSONAL_INFO_PAGE: 'personalInfo',
    MY_ORDER_PAGE: 'myOrder',
    BIND_BANK_CARD_PAGE: 'bindBankCard',
    RP_DETAIL_PAGE:"rpDetail",
    MERCHANT_ACTIVITY_LIST: "merchantActivityList",
    ACTIVITY_LIST_PAGE: "activityList",
    FILTER_PAGE: 'filter',
    INSTRUCTIONS_PAGE: 'instructions',
    BANKCARD_DETAIL: 'bankCardDetail',
    BANKCARD_LIST:'bankCardList',
    ACCOUNT_WITHDRAW_PAGE: 'accountWithdraw',
    BIG_RED_PACKET: "bigRedPacket",
    RECEIVE_RED_PACKET: "receiveRedPacket",
    SEND_RED_PACKET: "sendRedPacket",
    ACCOUNT_WITHDRAW_RESULT_PAGE: 'accountWithdrawResult',
    CHARGE_FLUX_RESULT: 'chargeFluxResult',
    ACCOUNT_TOPUP: 'accountTopup',
    RED_PACKET_RECORD: "redPacketRecord",
    RP_TITLE_STYLE: "rpTitleStyle",
    RED_PACKETS_READY_PAGE: "redPacketReady",
    RED_PACKETS_RESULT_PAGE:"redPacketResult",
    ACCOUNT_TOPUP_RESULT: 'accountTopupResult',
    TRADE_RECORD_LIST_PAGE: 'tradeRecordList',
    PAYMENT: 'payment',
    CREDITINPUT_PAGE: 'CreditCardInput',
    RED_PACKET_SQUARE: "redPacketSquare",
    CONTACTS_PAGE: 'contacts',
    RED_PACKET_RECORD_LIST: 'rpRecordList',
    TOUUP_RECORD_LIST:'topupRecordList',
    RED_PACKET_RECEIVER:'redPacketReceiver',
    RP_MONTH_DETAILRECORD:'rpMonthDetailRecord',
    NEW_BIND_BANKCARD:'newBindBankCard',
    NEW_USER_CERFITY:'userInfoCerfity',
};


