platform :ios, '8.0'
target 'XinguangWallet' do
inhibit_all_warnings!
pod 'YYKit', '~> 1.0.9'
pod 'AFNetworking', '~> 3.1.0'
pod 'GVUserDefaults', '~> 1.0.2'
pod 'SVProgressHUD', '~> 2.2.1'
pod 'Masonry', '~> 1.1.0'
pod 'IQKeyboardManager', '~> 5.0.2'
pod 'JPush', '~> 3.0.6'

pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'ART',
    'RCTActionSheet',
    'RCTAdSupport',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS',
    'DevSupport',
    'BatchedBridge',
    'RCTAnimation',
]
pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
end
