platform :ios, '8.0'
xcodeproj 'XinguangWallet.xcodeproj'
target 'XinguangWallet' do
inhibit_all_warnings!
pod 'YYKit', '~> 1.0.9'
pod 'AFNetworking', '~> 3.1.0'
pod 'GVUserDefaults', '~> 1.0.2'
pod 'SVProgressHUD', '~> 2.2.1'
pod 'Masonry', '~> 1.1.0'
pod 'IQKeyboardManager', '~> 5.0.2'
pod 'JPush', '~> 3.0.6'
pod 'SDWebImage', '~> 4.1.2'
pod 'MJRefresh', '~> 3.1.15.1'
pod 'AliyunOSSiOS', '~> 2.7.1'
pod 'UMengUShare/UI', '~> 6.4.7'
pod 'UMengUShare/Social/ReducedWeChat', '~> 6.4.7'

pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'ART',
    'RCTActionSheet',
    'RCTAdSupport',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS',
    'DevSupport',
    'BatchedBridge',
    'RCTAnimation',
]
pod 'react-native-camera', :path => '../node_modules/react-native-camera'

pod 'Picker', :path => '../node_modules/react-native-picker'

pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

pod 'lottie-ios', :path => '../node_modules/lottie-ios'
pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

end
